import React from 'react'
import Footer from './Components/Footer'
import Head from 'next/head'
import Image from 'next/image'
import style from '@/styles/Home.module.css'

// Images
import logo_familia from '../public/Images/logo_familia.png'
import home_2_1 from '../public/Images/home_2_1.jpg'
import home_2_2 from '../public/Images/home_2_2.jpg'
import boda_1 from '../public/Images/boda_1.jpg'
import flower_1 from '../public/Images/flower_1.png'
import flower_9 from '../public/Images/flower_9.png'
import portfolio_1 from '../public/Images/portfolio_1.jpg'
import portfolio_2 from '../public/Images/portfolio_2.jpg'
import portfolio_3 from '../public/Images/portfolio_3.jpg'
import portfolio_4 from '../public/Images/portfolio_4.jpg'
import img_1 from '../public/Images/img_1.jpg'
import flower_5 from '../public/Images/flower_5.png'
import img_3 from '../public/Images/img_3.jpg'
import flower_2 from '../public/Images/flower_2.png'
import flower_7 from '../public/Images/flower_7.png'
import flower_8 from '../public/Images/flower_8.png'
import img_12 from '../public/Images/img_12.jpg'
import img_11 from '../public/Images/img_11.jpg'
import img_10 from '../public/Images/img_10.jpg'
import img_9 from '../public/Images/img_9.jpg'
import left_arrow from '../public/Images/Left_Arrow.png'
import right_arrow from '../public/Images/Right_Arrow.png'







export default function Home_2() {
    return (
        <>

            <Head>
                <title>Home 2 - Bodas</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:100,100italic,200,200italic,300,300italic,400,400italic,500,500italic,600,600italic,700,700italic,800,800italic,900,900italic%7CMarcellus:regular%7CHomemade+Apple:regular" />
            </Head>

            <div className={style.overflow}>

                <div className={`${style.section_hero} wf_section`}>
                    <div className={style.content}>
                        <div className={style.hero_top}>
                            <div className={style.border_top} />
                            <Image
                                src={logo_familia}
                                loading="lazy"
                                alt=""
                                width={62}
                                className={style.image_subtitle}
                            />
                            <div className={style.subtitle}>
                                Nombre de la familia
                                <br />
                            </div>
                            <h1 className={style.heading_hero}>
                                Javier &amp; Fabiola
                            </h1>
                            <a href="/contact" className={style.link}>
                                Ver Más
                            </a>
                            <div className={style.border_down} />
                        </div>
                        <div className={style.hero___b}>
                            <div className={style.block_hero___b}>
                                <div
                                    className={style.overflow_hero___b_left}
                                    style={{
                                        willChange: "transform",
                                        transform:
                                            "translate3d(-3.4968%, 0.69936vh, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(-6.03678deg) skew(0deg, 0deg)",
                                        transformStyle: "preserve-3d"
                                    }}
                                >
                                    <Image
                                        src={home_2_1}
                                        loading="lazy"
                                        style={{
                                            opacity: 1,
                                            willChange: "transform",
                                            transform:
                                                "translate3d(0px, 0px, 0px) scale3d(1.05061, 1.05061, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)",
                                            transformStyle: "preserve-3d"
                                        }}
                                        srcSet="https://assets.website-files.com/6109925e44b6ab8a7601f26a/6111b971be7bddceae1d154c_home_b2-p-500.jpeg 500w, https://assets.website-files.com/6109925e44b6ab8a7601f26a/6111b971be7bddceae1d154c_home_b2-p-800.jpeg 800w, https://assets.website-files.com/6109925e44b6ab8a7601f26a/6111b971be7bddceae1d154c_home_b2.jpg 803w"
                                        sizes="(max-width: 479px) 51vw, (max-width: 767px) 49vw, 375.1875px"
                                        alt=""
                                        className={style.image_hero___b}
                                    />
                                </div>
                                <div
                                    className={style.overflow_hero___b_right}
                                    style={{
                                        willChange: "transform",
                                        transform:
                                            "translate3d(3.4968%, 0.69936vh, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(6.03678deg) skew(0deg, 0deg)",
                                        transformStyle: "preserve-3d"
                                    }}
                                >
                                    <Image
                                        src={boda_1}
                                        loading="lazy"
                                        style={{
                                            opacity: 1,
                                            willChange: "transform",
                                            transform:
                                                "translate3d(0px, 0px, 0px) scale3d(1.05061, 1.05061, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)",
                                            transformStyle: "preserve-3d"
                                        }}
                                        srcSet="https://assets.website-files.com/6109925e44b6ab8a7601f26a/610b4126b00a600bfdb60d4b_home_a2-p-500.jpeg 500w, https://assets.website-files.com/6109925e44b6ab8a7601f26a/610b4126b00a600bfdb60d4b_home_a2-p-800.jpeg 800w, https://assets.website-files.com/6109925e44b6ab8a7601f26a/610b4126b00a600bfdb60d4b_home_a2.jpg 803w"
                                        sizes="(max-width: 479px) 51vw, (max-width: 767px) 49vw, 375.1875px"
                                        alt=""
                                        className={style.image_hero___b}
                                    />
                                </div>
                                <div
                                    className={style.overflow_hero___b}
                                    style={{
                                        willChange: "transform",
                                        transform:
                                            "translate3d(0px, 0.34968vh, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)",
                                        transformStyle: "preserve-3d"
                                    }}
                                >
                                    <Image
                                        src={home_2_2}
                                        loading="lazy"
                                        style={{
                                            opacity: 1,
                                            willChange: "transform",
                                            transform:
                                                "translate3d(0px, 0px, 0px) scale3d(1.05061, 1.05061, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)",
                                            transformStyle: "preserve-3d"
                                        }}
                                        srcSet="https://assets.website-files.com/6109925e44b6ab8a7601f26a/6111b9713dd3cba82cce3b0e_home_b1-p-500.jpeg 500w, https://assets.website-files.com/6109925e44b6ab8a7601f26a/6111b9713dd3cba82cce3b0e_home_b1-p-800.jpeg 800w, https://assets.website-files.com/6109925e44b6ab8a7601f26a/6111b9713dd3cba82cce3b0e_home_b1.jpg 908w"
                                        sizes="(max-width: 479px) 77vw, (max-width: 767px) 73vw, 560px"
                                        alt=""
                                        className={style.image_hero___b}
                                    />
                                </div>
                                <Image
                                    src={flower_1}
                                    loading="eager"
                                    height={210}
                                    style={{
                                        opacity: 1,
                                        willChange: "transform",
                                        transform:
                                            "translate3d(5.85288%, 0.03678vh, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(-4.20256deg) skew(0deg, 0deg)",
                                        transformStyle: "preserve-3d"
                                    }}
                                    alt=""
                                    className={style.flower_hero___b1}
                                />
                                <Image
                                    src={flower_9}
                                    loading="eager"
                                    height={300}
                                    style={{
                                        opacity: 1,
                                        willChange: "transform",
                                        transform:
                                            "translate3d(0px, 1.36194vh, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(30.7974deg) skew(0deg, 0deg)",
                                        transformStyle: "preserve-3d"
                                    }}
                                    className={style.flower_hero___b2}
                                />
                            </div>
                        </div>
                    </div>
                </div>


                <div className={`${style.section} wf-section`}>
                    <div className={style.content}>
                        <div className={`${style.block_heading} ${style.margin}`}>
                            <Image
                                src={logo_familia}
                                loading="lazy"
                                alt=""
                                width={62}
                                className={style.image_subtitle}
                                style={{
                                    transform:
                                        "translate3d(0px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)",
                                    transformStyle: "preserve-3d",
                                    opacity: 1
                                }}
                            />
                            <div className={style.subtitle}>
                                Nombre de la Familia
                                <br />
                            </div>
                            <h2 className={style.heading}>Eventos</h2>
                        </div>
                        <div className={`${style.collection_list_wrapper___portfolio} ${style.w_dyn_list}`}>
                            <div role="list" className={`${style.collection_list___portfolio} ${style.w_dyn_items}`}>
                                <div role="listitem" className={`${style.collection_item___portfolio} ${style.w_dyn_item}`}>
                                    <a
                                        href="#"
                                        className={`${style.overflow_portfolio} ${style.w_inline_block}`}
                                    >
                                        <Image
                                            loading="lazy"
                                            style={{ opacity: 1 }}
                                            src={portfolio_1}
                                            alt="Jennifer & Oliver"
                                            sizes="(max-width: 479px) 100vw, (max-width: 767px) 46vw, (max-width: 991px) 23vw, 22vw"
                                            srcSet="https://assets.website-files.com/610ded14770a9b661a8e0dcd/610dee1a9558a9c39348d5d3_portfolio_1-p-500.jpeg 500w, https://assets.website-files.com/610ded14770a9b661a8e0dcd/610dee1a9558a9c39348d5d3_portfolio_1.jpg 628w"
                                            className={style.image_portfolio}
                                        />
                                    </a>
                                    <div className={style.block_portfolio}>
                                        <a
                                            href="#"
                                            className={`${style.link_portfolio} ${style.w_inline_block}`}
                                        >
                                            <h5 className={style.heading_portfolio}>Ceremonia</h5>
                                        </a>
                                        <a href="#" className={style.link}>
                                            Ver Más
                                        </a>
                                    </div>
                                </div>
                                <div role="listitem" className={`${style.collection_item___portfolio} ${style.w_dyn_item}`}>
                                    <a
                                        href="#"
                                        className={`${style.overflow_portfolio} ${style.w_inline_block}`}
                                    >
                                        <Image
                                            loading="lazy"
                                            src={portfolio_2}
                                            alt="Briana & Richard"
                                            className={style.image_portfolio}
                                        />
                                    </a>
                                    <div className={style.block_portfolio}>
                                        <a
                                            href="#"
                                            className={`${style.link_portfolio} ${style.w_inline_block}`}
                                        >
                                            <h5 className={style.heading_portfolio}>Salon de Fiesta</h5>
                                        </a>
                                        <a href="#" className={style.link}>
                                            Ver Más
                                        </a>
                                    </div>
                                </div>
                                <div role="listitem" className={`${style.collection_item___portfolio} ${style.w_dyn_item}`}>
                                    <a
                                        href="#"
                                        className={`${style.overflow_portfolio} ${style.w_inline_block}`}
                                    >
                                        <Image
                                            loading="lazy"
                                            style={{ opacity: 1 }}
                                            src={portfolio_3}
                                            alt="Anne & Cameron"
                                            sizes="(max-width: 479px) 100vw, (max-width: 767px) 46vw, (max-width: 991px) 23vw, 22vw"
                                            srcSet="https://assets.website-files.com/610ded14770a9b661a8e0dcd/610dedc29c43a564818d5bd1_portfolio_3-p-500.jpeg 500w, https://assets.website-files.com/610ded14770a9b661a8e0dcd/610dedc29c43a564818d5bd1_portfolio_3.jpg 628w"
                                            className={style.image_portfolio}
                                        />
                                    </a>
                                    <div className={style.block_portfolio}>
                                        <a
                                            href="#"
                                            className={`${style.link_portfolio} ${style.w_inline_block}`}
                                        >
                                            <h5 className={style.heading_portfolio}>Boda</h5>
                                        </a>
                                        <a href="#" className={style.link}>
                                            Ver Más
                                        </a>
                                    </div>
                                </div>
                                <div role="listitem" className={`${style.collection_item___portfolio} ${style.w_dyn_item}`}>
                                    <a
                                        href="#"
                                        className={`${style.overflow_portfolio} ${style.w_inline_block}`}
                                    >
                                        <Image
                                            loading="lazy"
                                            style={{ opacity: 1 }}
                                            src={portfolio_4}
                                            alt="Linda & Charles"
                                            sizes="(max-width: 479px) 100vw, (max-width: 767px) 46vw, (max-width: 991px) 23vw, 22vw"
                                            srcSet="https://assets.website-files.com/610ded14770a9b661a8e0dcd/610ded65ec6be73dc143021b_portfolio_4-p-500.jpeg 500w, https://assets.website-files.com/610ded14770a9b661a8e0dcd/610ded65ec6be73dc143021b_portfolio_4.jpg 628w"
                                            className={style.image_portfolio}
                                        />
                                    </a>
                                    <div className={style.block_portfolio}>
                                        <a
                                            href="#"
                                            className={`${style.link_portfolio} ${style.w_inline_block}`}
                                        >
                                            <h5 className={style.heading_portfolio}>Iglesia</h5>
                                        </a>
                                        <a href="#" className={style.link}>
                                            Ver Más
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <a href="#" className={`${style.button} ${style.w_button}`}>
                            Ver todo el portafolio
                        </a>
                    </div>
                </div>


                <div className={`${style.section} wf-section`}>
                    <div className={style.content}>
                        <div className={`${style.w_layout_grid} ${style.grid_2_columns}`}>
                            <div className={style.block_text}>
                                <Image
                                    src={logo_familia}
                                    loading="lazy"
                                    alt=""
                                    width={62}
                                    className={style.image_subtitle}
                                    style={{
                                        transform:
                                            "translate3d(0px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)",
                                        transformStyle: "preserve-3d",
                                        opacity: 1
                                    }}
                                />
                                <div className={style.subtitle}>
                                    ella
                                    <br />
                                </div>
                                <h2 className={style.heading}>Fabiola</h2>
                                <p className={style.paragraph}>
                                    Cras urna sed purus magna morbi morbi congue suspendisse. Est faucibus
                                    hendrerit donec nisi, feugiat suscipit eu, sit. Orci euismod nibh.
                                </p>
                                <a href="#" className={`${style.button} ${style.w_button}`}>
                                    Ver Más
                                </a>
                            </div>
                            <div
                                className={style.block_image}
                            >
                                <div
                                    className={style.overflow_image}
                                    style={{
                                        willChange: "transform",
                                        transform:
                                            "translate3d(0px, -0.50898vh, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0.8483deg) skew(0deg, 0deg)",
                                        transformStyle: "preserve-3d"
                                    }}
                                >
                                    <Image
                                        src={img_1}
                                        loading="lazy"
                                        style={{
                                            opacity: 1,
                                            willChange: "transform",
                                            transform:
                                                "translate3d(0px, 0px, 0px) scale3d(1.06228, 1.06228, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)",
                                            transformStyle: "preserve-3d"
                                        }}
                                        srcSet="https://assets.website-files.com/6109925e44b6ab8a7601f26a/610c80ecf92b9227f9cf593e_img_1-p-500.jpeg 500w, https://assets.website-files.com/6109925e44b6ab8a7601f26a/610c80ecf92b9227f9cf593e_img_1-p-800.jpeg 800w, https://assets.website-files.com/6109925e44b6ab8a7601f26a/610c80ecf92b9227f9cf593e_img_1.jpg 805w"
                                        sizes="(max-width: 767px) 80vw, (max-width: 991px) 81vw, 77vw"
                                        alt=""
                                        className={style.image}
                                    />
                                </div>
                                <Image
                                    src={flower_5}
                                    loading="eager"
                                    style={{
                                        opacity: 1,
                                        willChange: "transform",
                                        transform:
                                            "translate3d(0.6068%, -0.8483vh, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(-31.5309deg) skew(0deg, 0deg)",
                                        transformStyle: "preserve-3d"
                                    }}
                                    width={397}
                                    height={426}
                                    alt=""
                                    className={style.flower___a}
                                />
                            </div>
                        </div>
                    </div>
                </div>

                <div className={`${style.section} wf-section`}>
                    <div className={style.content}>
                        <div className={`${style.w_layout_grid} ${style.grid_2_columns}`}>
                            <div
                                className={style.block_image}
                            >
                                <div
                                    className={style.overflow_image}
                                    style={{
                                        willChange: "transform",
                                        transform:
                                            "translate3d(0px, -0.29538vh, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0.4923deg) skew(0deg, 0deg)",
                                        transformStyle: "preserve-3d"
                                    }}
                                >
                                    <Image
                                        src={img_3}
                                        loading="lazy"
                                        style={{
                                            opacity: 1,
                                            willChange: "transform",
                                            transform:
                                                "translate3d(0px, 0px, 0px) scale3d(1.06762, 1.06762, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)",
                                            transformStyle: "preserve-3d"
                                        }}
                                        srcSet="https://assets.website-files.com/6109925e44b6ab8a7601f26a/610c80ec3798f1029502d222_img_3-p-500.jpeg 500w, https://assets.website-files.com/6109925e44b6ab8a7601f26a/610c80ec3798f1029502d222_img_3-p-800.jpeg 800w, https://assets.website-files.com/6109925e44b6ab8a7601f26a/610c80ec3798f1029502d222_img_3.jpg 805w"
                                        sizes="(max-width: 767px) 80vw, (max-width: 991px) 81vw, 77vw"
                                        alt=""
                                        className={style.image}
                                    />
                                </div>
                                <Image
                                    src={flower_2}
                                    loading="eager"
                                    style={{
                                        opacity: 1,
                                        willChange: "transform",
                                        transform:
                                            "translate3d(-4.0154%, 0.86001vh, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(-0.57536deg) skew(0deg, 0deg)",
                                        transformStyle: "preserve-3d"
                                    }}
                                    width={260}
                                    height={251}
                                    alt=""
                                    className={style.flower___b}
                                />
                            </div>
                            <div className={style.block_text}>
                                <Image
                                    src={logo_familia}
                                    loading="lazy"
                                    alt=""
                                    width={62}
                                    className={style.image_subtitle}
                                    style={{
                                        transform:
                                            "translate3d(0px, 0px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)",
                                        transformStyle: "preserve-3d",
                                        opacity: 1
                                    }}
                                />
                                <div className={style.subtitle}>
                                    él
                                    <br />
                                </div>
                                <h2 className={style.heading}>
                                    Javier
                                </h2>
                                <p className={style.paragraph}>
                                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Enim
                                    tincidunt magna viverra nibh scelerisque lorem ipsum adipiscing dolor.
                                </p>
                                <a href="#" className={`${style.button} ${style.w_button}`}>
                                    Ver Más
                                </a>
                            </div>
                        </div>
                    </div>
                </div>

                <div className={`${style.section_hero} wf-section_s`}>
                    <div className={`${style.content} ${style.wide}`}>
                        <div className={style.hero___c}>
                            <div className={style.block_hero___c}>
                                <div className={style.text_hero___c}>
                                    <Image
                                        src={logo_familia}
                                        loading="lazy"
                                        alt=""
                                        width={62}
                                        className={style.image_subtitle}
                                    />
                                    <div className={style.subtitle}>
                                        Nombre de la Familia
                                        <br />
                                    </div>
                                    <h1 className={style.heading_hero}>
                                        Titulo                                    </h1>
                                    <p className={style.paragraph}>
                                        We are invested in artful beauty, a strong logistical foundation
                                        with collaborative efforts constantly producing extraordinary
                                        events.
                                    </p>
                                    <a href="#" className={style.link}>
                                        Ver Más
                                    </a>
                                </div>
                                <Image
                                    src={flower_7}
                                    loading="eager"
                                    alt=""
                                    width={309}
                                    height={357}
                                    className={style.flower_hero___c1}
                                />
                                <Image
                                    src={flower_8}
                                    loading="eager"
                                    alt=""
                                    width={288}
                                    height={340}
                                    className={style.flower_hero___c2}
                                />
                            </div>
                            <div className={`${style.w_layout_grid} ${style.grid_hero___c}`}>
                                <a
                                    href="#"
                                    className={`${style.lightbox_link} ${style.w_inline_block} ${style.w_lightbox}`}
                                >
                                    <Image
                                        src={img_12}
                                        loading="lazy"
                                        data-w-id="ef308a03-b080-64f0-1883-9a8eb54c0ca0"
                                        srcSet="https://assets.website-files.com/6109925e44b6ab8a7601f26a/610df60220b64c18e8457e38_img_12-p-500.jpeg 500w, https://assets.website-files.com/6109925e44b6ab8a7601f26a/610df60220b64c18e8457e38_img_12-p-800.jpeg 800w, https://assets.website-files.com/6109925e44b6ab8a7601f26a/610df60220b64c18e8457e38_img_12.jpg 805w"
                                        sizes="(max-width: 479px) 90vw, (max-width: 767px) 89vw, 90vw"
                                        alt=""
                                        className={style.image_lightbox}
                                    />
                                </a>
                                <a
                                    href="#"
                                    className={`${style.lightbox_link} ${style.w_inline_block} ${style.w_lightbox}`}
                                >
                                    <Image
                                        src={img_11}
                                        loading="lazy"
                                        data-w-id="90f47247-e4d1-fb54-f265-43b141245d69"
                                        srcSet="https://assets.website-files.com/6109925e44b6ab8a7601f26a/610c995bd5f573418e62eb65_img_11-p-800.jpeg 800w, https://assets.website-files.com/6109925e44b6ab8a7601f26a/610c995bd5f573418e62eb65_img_11.jpg 1000w"
                                        sizes="(max-width: 479px) 90vw, (max-width: 767px) 89vw, 90vw"
                                        alt=""
                                        className={style.image_lightbox}
                                    />
                                </a>
                                <a
                                    href="#"
                                    className={`${style.lightbox_link} ${style.w_inline_block} ${style.w_lightbox}`}
                                >
                                    <Image
                                        src={img_1}
                                        loading="lazy"
                                        srcSet="https://assets.website-files.com/6109925e44b6ab8a7601f26a/610c80ecf92b9227f9cf593e_img_1-p-500.jpeg 500w, https://assets.website-files.com/6109925e44b6ab8a7601f26a/610c80ecf92b9227f9cf593e_img_1-p-800.jpeg 800w, https://assets.website-files.com/6109925e44b6ab8a7601f26a/610c80ecf92b9227f9cf593e_img_1.jpg 805w"
                                        sizes="(max-width: 479px) 90vw, (max-width: 767px) 89vw, 90vw"
                                        alt=""
                                        className={style.image_lightbox}
                                    />
                                </a>
                                <a
                                    href="#"
                                    className={`${style.lightbox_link} ${style.w_inline_block} ${style.w_lightbox}`}
                                >
                                    <Image
                                        src={img_10}
                                        loading="lazy"
                                        alt=""
                                        className={style.image_lightbox}
                                    />
                                </a>
                                <a
                                    href="#"
                                    className={`${style.lightbox_link} ${style.w_inline_block} ${style.w_lightbox}`}
                                >
                                    <Image
                                        src={img_3}
                                        loading="lazy"
                                        srcSet="https://assets.website-files.com/6109925e44b6ab8a7601f26a/610c80ec3798f1029502d222_img_3-p-500.jpeg 500w, https://assets.website-files.com/6109925e44b6ab8a7601f26a/610c80ec3798f1029502d222_img_3-p-800.jpeg 800w, https://assets.website-files.com/6109925e44b6ab8a7601f26a/610c80ec3798f1029502d222_img_3.jpg 805w"
                                        sizes="(max-width: 479px) 90vw, (max-width: 767px) 89vw, 90vw"
                                        alt=""
                                        className={style.image_lightbox}
                                    />
                                </a>
                                <a
                                    href="#"
                                    className={`${style.lightbox_link} ${style.w_inline_block} ${style.w_lightbox}`}
                                >
                                    <Image
                                        src={img_9}
                                        loading="lazy"
                                        srcSet="https://assets.website-files.com/6109925e44b6ab8a7601f26a/610c995b895b7a5ff922e5e9_img_9-p-800.jpeg 800w, https://assets.website-files.com/6109925e44b6ab8a7601f26a/610c995b895b7a5ff922e5e9_img_9.jpg 1000w"
                                        sizes="(max-width: 479px) 90vw, (max-width: 767px) 89vw, 90vw"
                                        alt=""
                                        className={style.image_lightbox}
                                    />
                                </a>
                            </div>
                        </div>
                    </div>
                </div>



                {/* Testimonios */}
                <div className={`${style.section} ${style.shape_section}`}>
                    <div className={style.roadmap_shape_testimonial} />
                    <div className={style.content}>
                        <div className={`${style.block_heading} ${style.margin}`}>
                            <Image
                                src={logo_familia}
                                loading="lazy"
                                alt=""
                                width={62}
                                className={style.image_subtitle}
                            />
                            <div className={style.subtitle}>
                                Testimonios
                                <br />
                            </div>
                            <h2 className={style.heading}>Lo que dicen sobre ellos</h2>
                        </div>
                        <div className={`${style.slider_testimonials} ${style.w_slider}`}>
                            <div className={`mask ${style.w_slider_mask}`} id="w-slider-mask-0">
                                <div className={`${style.slide} ${style.w_slide}`}>
                                    <div className={style.testimonial} aria-hidden="true">
                                        <Image
                                            src={flower_1}
                                            loading="lazy"
                                            alt=""
                                            width={78}
                                            height={78}
                                            className={style.image_testimonial}
                                        />
                                        <p className={style.paragraph_testimonial} aria-hidden="true">
                                            “Turpis nullam dictum semper non. Sit libero venenatis nec, id
                                            viverra adipiscing non ultrices volutpat. Eleifend mi augue mi
                                            auctor diam diam. Mattis elementum ullamcorper gravida id velit
                                            mauris adipiscing sed. Sollicitudin in laoreet etiam.”
                                        </p>
                                        <div className={style.signature_testimonial} aria-hidden="true">
                                            Javier Alonso
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div
                                className={`${style.left_arrow} ${style.w_slider_arrow_left}`}
                                role="button"
                            >
                                <Image
                                    src={left_arrow}
                                    loading="lazy"
                                    width={23}
                                    alt=""
                                    className={style.arrow}
                                />
                            </div>
                            <div
                                className={`${style.right_arrow} ${style.w_slider_arrow_right}`}
                            >
                                <Image
                                    src={right_arrow}
                                    loading="lazy"
                                    width={23}
                                    alt=""
                                    className={style.arrow}
                                />
                            </div>
                        </div>
                    </div>
                </div>



                <Footer />

            </div>


        </>
    )
}
