import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import style from '../styles/Home.module.css'
import Footer from './Components/Footer'

const inter = Inter({ subsets: ['latin'] })

// Images
import logo_familia from '../public/Images/logo_familia.png'
import boda_1 from '../public/Images/boda_1.jpg'
import flower_1 from '../public/Images/flower_1.png'
import img_1 from '../public/Images/img_1.jpg'
import img_3 from '../public/Images/img_3.jpg'
import flower_2 from '../public/Images/flower_2.png'
import flower_5 from '../public/Images/flower_5.png'
import img_12 from '../public/Images/img_12.jpg'
import img_11 from '../public/Images/img_11.jpg'
import img_10 from '../public/Images/img_10.jpg'
import img_9 from '../public/Images/img_9.jpg'
import left_arrow from '../public/Images/Left_Arrow.png'
import right_arrow from '../public/Images/Right_Arrow.png'
import home_a1 from '../public/Images/home_a1.jpg'
import home_a3 from '../public/Images/home_a3.jpg'
import extra from '../public/Images/extra.png'
import img_2 from '../public/Images/img_2.jpg'
import img_4 from '../public/Images/img_4.jpg'
import flower_3 from '../public/Images/flower_3.png'
import img_8 from '../public/Images/img_8.jpg'
import img_5 from '../public/Images/img_5.jpg'
import img_6 from '../public/Images/img_5.jpg'
import img_7 from '../public/Images/img_7.jpg'





export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:100,100italic,200,200italic,300,300italic,400,400italic,500,500italic,600,600italic,700,700italic,800,800italic,900,900italic%7CMarcellus:regular%7CHomemade+Apple:regular" media="all" />
        <link
          href="https://fonts.googleapis.com/css2?family=Krona+One&display=optional"
          rel="stylesheet"
        />
      </Head>

      {/* S1 */}
      <div className={`${style.section_hero} ${style.wf_section}`}>
        <div className={`${style.content} ${style.wide}`}>
          <div data-w-id="431537a0-a345-831e-c502-7cecf11d9aa4" className={style.hero___a}>
            <div className={`${style.w_layout_grid} ${style.grid_hero___a}`}>
              <div className={style.overflow_hero___a}>
                <Image
                  src={home_a1}
                  loading="lazy"
                  srcSet="https://assets.website-files.com/6109925e44b6ab8a7601f26a/610b4126a35dd31cb8da134d_home_a1-p-500.jpeg 500w, https://assets.website-files.com/6109925e44b6ab8a7601f26a/610b4126a35dd31cb8da134d_home_a1-p-800.jpeg 800w, https://assets.website-files.com/6109925e44b6ab8a7601f26a/610b4126a35dd31cb8da134d_home_a1.jpg 803w"
                  sizes="(max-width: 479px) 96vw, (max-width: 767px) 95vw, 96vw"
                  alt=""
                  className={style.image_hero___a}
                />
              </div>
              <div className={style.overflow_hero___a}>
                <Image
                  src={boda_1}
                  loading="lazy"
                  srcSet="https://assets.website-files.com/6109925e44b6ab8a7601f26a/610b4126b00a600bfdb60d4b_home_a2-p-500.jpeg 500w, https://assets.website-files.com/6109925e44b6ab8a7601f26a/610b4126b00a600bfdb60d4b_home_a2-p-800.jpeg 800w, https://assets.website-files.com/6109925e44b6ab8a7601f26a/610b4126b00a600bfdb60d4b_home_a2.jpg 803w"
                  sizes="(max-width: 479px) 96vw, (max-width: 767px) 95vw, 96vw"
                  alt=""
                  className={style.image_hero___a}
                />
              </div>
              <div className={style.overflow_hero___a}>
                <Image
                  src={home_a3}
                  loading="lazy"
                  srcSet="https://assets.website-files.com/6109925e44b6ab8a7601f26a/610b412633b829429dbd6b27_home_a3-p-500.jpeg 500w, https://assets.website-files.com/6109925e44b6ab8a7601f26a/610b412633b829429dbd6b27_home_a3-p-800.jpeg 800w, https://assets.website-files.com/6109925e44b6ab8a7601f26a/610b412633b829429dbd6b27_home_a3.jpg 803w"
                  sizes="(max-width: 479px) 96vw, (max-width: 767px) 95vw, 96vw"
                  alt=""
                  className={style.image_hero___a}
                />
              </div>
            </div>
            <div className={style.block_hero___a}>
              <div className={style.text_hero___a}>
                <Image
                  src={logo_familia}
                  loading="lazy"
                  alt=""
                  width={62}
                  className={style.image_subtitle}
                />
                <div className={style.subtitle}>
                  Nombre de la Familia
                  <br />
                </div>
                <h1 className={style.heading_hero}>
                  Javier Alonso <br />
                  &amp; Eva
                </h1>
                <a href="#" className={style.link}>
                  Ver Álbum
                </a>
              </div>
              <Image
                src={flower_1}
                loading="eager"
                style={{
                  opacity: 1,
                  willChange: "transform",
                  transform:
                    "translate3d(13.0261%, -1.54248vh, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(7.7124deg) skew(0deg, 0deg)",
                  transformStyle: "preserve-3d"
                }}
                data-w-id="b8809a05-1ba3-b36d-7d7c-5812489a4179"
                alt=""
                className={style.flower_hero___a}
              />
            </div>
          </div>
        </div>
      </div>

      {/* S2 */}
      <div className={`${style.section} ${style.wf_section}`}>
        <div className={style.content}>
          <div className={style.block_extra}>
            <Image
              src={extra}
              loading="lazy"
              alt=""
              width={70}
              className={style.image_extra}
            />
            <h4 className={style.heading_extra}>
              Su boda debe ser inolvidable, profundamente romántica, exquisitamente bella y totalmente {"suya"}.
            </h4>
            <p className={style.paragraph}>
              Lectus sit turpis iaculis eu non sed turpis suscipit facilisi. Lorem
              morbi non morbi id aliquam. Urna adipiscing odio.
            </p>
            <div className={style.signature}>Javier Alonso</div>
          </div>
        </div>
      </div>

      {/* S3 */}
      <section className={style.pre_wedding}>
        <div className={`${style.section} ${style.wf_section}`}>
          <div className={style.content}>
            <div className={style.block_extra}>
              <Image
                src={extra}
                loading="lazy"
                alt=""
                width={70}
                className={style.image_extra}
              />
              <h4 className={style.heading_extra}>
                Su boda debe ser inolvidable.
              </h4>
              <div className={style.signature}>Javier Alonso</div>
            </div>
          </div>
        </div>
        <div className={style.video_area}>
          <video
            autoPlay={true}
            loop
            muted
          // poster="https://assets.codepen.io/6093409/river.jpg"
          >
            <source src="/Images/boda.mp4" type="video/mp4" />
          </video>
        </div>
      </section>

      {/* S4 */}
      <div className={`${style.section} ${style.shape_section}`}>
        <div className={style.roadmap_shape_left} />
        <div className={style.roadmap_shape_right} />
        <div className={style.content}>
          <div className={`${style.w_layout_grid} ${style.grid_3_columns}`}>
            <div className={style.service}>
              <a
                href="#"
                className={`${style.overflow_service} ${style.w_inline_block}`}>
                <Image
                  src={img_1}
                  loading="lazy"
                  srcSet="https://assets.website-files.com/6109925e44b6ab8a7601f26a/610c80ecf92b9227f9cf593e_img_1-p-500.jpeg 500w, https://assets.website-files.com/6109925e44b6ab8a7601f26a/610c80ecf92b9227f9cf593e_img_1-p-800.jpeg 800w, https://assets.website-files.com/6109925e44b6ab8a7601f26a/610c80ecf92b9227f9cf593e_img_1.jpg 805w"
                  sizes="(max-width: 479px) 77vw, (max-width: 767px) 76vw, 96vw"
                  alt=""
                  className={style.image_service}
                />
              </a>
              <div className={style.block_service}>
                <a
                  href="#"
                  className={`${style.link_service} ${style.w_inline_block}`}
                >
                  <h4 className={style.heading_service}>Ceremonia</h4>
                </a>
                <p className={style.paragraph_service}>
                  Adipiscing mauris sed metus dictum eget morbi aliquet. Sit neque
                  tempus eget dictum velit tristique.
                </p>
                <a href="#" className={style.link}>
                  ver más
                </a>
              </div>
            </div>
            <div className={style.service}>
              <a
                href="#"
                className={`${style.overflow_service} ${style.w_inline_block}`}>
                <Image
                  src={img_2}
                  loading="lazy"
                  srcSet="https://assets.website-files.com/6109925e44b6ab8a7601f26a/610c80eca585763bdb6fbc56_img_2-p-500.jpeg 500w, https://assets.website-files.com/6109925e44b6ab8a7601f26a/610c80eca585763bdb6fbc56_img_2-p-800.jpeg 800w, https://assets.website-files.com/6109925e44b6ab8a7601f26a/610c80eca585763bdb6fbc56_img_2.jpg 805w"
                  sizes="(max-width: 479px) 77vw, (max-width: 767px) 76vw, 96vw"
                  alt=""
                  className={style.image_service}
                />
              </a>
              <div className={style.block_service}>
                <a
                  href="#"
                  className={`${style.link_service} ${style.w_inline_block}`}
                >
                  <h4 className={style.heading_service}>Iglesia</h4>
                </a>
                <p className={style.paragraph_service}>
                  Lectus sit turpis iaculis eu non sed turpis suscipit facilisi. Lorem
                  morbi non morbi id aliquam. Urna adipiscing odio.
                </p>
                <a href="#" className={style.link}>
                  ver más
                </a>
              </div>
            </div>
            <div className={style.service}>
              <a
                href="#"
                className={`${style.overflow_service} ${style.w_inline_block}`}>
                <Image
                  src={img_3}
                  loading="lazy"
                  srcSet="https://assets.website-files.com/6109925e44b6ab8a7601f26a/610c80ec3798f1029502d222_img_3-p-500.jpeg 500w, https://assets.website-files.com/6109925e44b6ab8a7601f26a/610c80ec3798f1029502d222_img_3-p-800.jpeg 800w, https://assets.website-files.com/6109925e44b6ab8a7601f26a/610c80ec3798f1029502d222_img_3.jpg 805w"
                  sizes="(max-width: 479px) 77vw, (max-width: 767px) 76vw, 96vw"
                  alt=""
                  className={style.image_service}
                />
              </a>
              <div className={style.block_service}>
                <a
                  href="#"
                  className={`${style.link_service} ${style.w_inline_block}`}
                >
                  <h4 className={style.heading_service}>Sesión de Fotos</h4>
                </a>
                <p className={style.paragraph_service}>
                  Tristique sodales consectetur lectus feugiat molestie. Condimentum
                  eu faucibus dictum adipiscing.
                </p>
                <a href="#" className={style.link}>
                  ver más
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* S5 */}
      <div className={`${style.section} ${style.shape_section}`}>
        <div className={style.roadmap_shape_center} />
        <div className={style.content}>
          <div
            data-w-id="53b697f0-023e-7f03-d53c-bf4f4b3206cd"
            className={`${style.w_layout_grid} ${style.grid_postcard}`}
          >
            <div
              id={style["w-node-a38a8908-1dc6-e0b5-39a4-e35f06688720-6c01f26c"]}
              className={style.postcard___block_right}
            >
              <div className={style.postcard_text}>
                <Image
                  src={logo_familia}
                  loading="lazy"
                  alt=""
                  width={62}
                  className={style.image_subtitle}
                />
                <div className={style.subtitle}>
                  Ella
                  <br />
                </div>
                <h2 className={style.heading}>
                  Historia Sobre Ella
                </h2>
                <p className={style.paragraph}>
                  Cras urna sed purus magna morbi morbi congue suspendisse. Est
                  faucibus hendrerit donec nisi, feugiat suscipit eu, sit. Orci
                  euismod nibh.
                </p>
                <a href="/about/about-a" className={`${style.button} ${style.w_button}`}>
                  Más sobre ella
                </a>
              </div>
            </div>
            <div
              id={style["w-node-d2924451-e09a-bd31-2cf5-d17c83bb6e82-6c01f26c"]}
              className={style.postcard___image}
              style={{
                willChange: "transform",
                transform:
                  "translate3d(0px, 0.3012vh, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)",
                transformStyle: "preserve-3d"
              }}
            >
              <div className={style.overflow_image}>
                <Image
                  src={img_4}
                  loading="lazy"
                  srcSet="https://assets.website-files.com/6109925e44b6ab8a7601f26a/610c869f09424720d94e3a6f_img_4-p-500.jpeg 500w, https://assets.website-files.com/6109925e44b6ab8a7601f26a/610c869f09424720d94e3a6f_img_4-p-800.jpeg 800w, https://assets.website-files.com/6109925e44b6ab8a7601f26a/610c869f09424720d94e3a6f_img_4.jpg 805w"
                  sizes="(max-width: 479px) 96vw, (max-width: 767px) 95vw, 96vw"
                  alt=""
                  className={style.image}
                />
              </div>
              <Image
                src={flower_1}
                loading="eager"
                alt=""
                className={style.flower_postcard___a}
              />
              <Image
                src={flower_3}
                loading="eager"
                alt=""
                className={style.flower_postcard___b}
              />
            </div>
          </div>
        </div>
      </div>

      {/* S6 */}
      <div className={`${style.section} ${style.shape_section}`}>
        <div className={style.roadmap_shape_left} />
        <div className={style.roadmap_shape_right} />
        <div className={`${style.content} ${style.wide}`}>
          <div className={style.block_heading}>
            <Image
              src={logo_familia}
              loading="lazy"
              alt=""
              width={62}
              className={style.image_subtitle}
            />
            <div className={style.subtitle}>
              Galleries
              <br />
            </div>
            <h2 className={style.heading}>Galería</h2>
            <p className={style.paragraph}>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cursus
              hendrerit dolor lorem risus et tellus magna amet morbi. Elit risus in
              sed dolor diam.
            </p>
          </div>
          <div className={`${style.w_layout_grid} ${style.grid_galleries}`}>
            <div className={`${style.w_layout_grid} ${style.grid_galleries___row}`}>
              <a href="#" className={`${style.lightbox_link} ${style.w_inline_block} ${style.w_lightbox}`}>
                <Image
                  src={img_1}
                  loading="lazy"
                  style={{ opacity: 1 }}
                  srcSet="https://assets.website-files.com/6109925e44b6ab8a7601f26a/610c80ecf92b9227f9cf593e_img_1-p-500.jpeg 500w, https://assets.website-files.com/6109925e44b6ab8a7601f26a/610c80ecf92b9227f9cf593e_img_1-p-800.jpeg 800w, https://assets.website-files.com/6109925e44b6ab8a7601f26a/610c80ecf92b9227f9cf593e_img_1.jpg 805w"
                  sizes="(max-width: 479px) 96vw, (max-width: 767px) 95vw, 96vw"
                  alt=""
                  className={style.image_lightbox}
                />
              </a>
              <a href="#" className={`${style.lightbox_link} ${style.w_inline_block} ${style.w_lightbox}`}>
                <Image
                  src={img_11}
                  loading="lazy"
                  style={{ opacity: 1 }}
                  srcSet="https://assets.website-files.com/6109925e44b6ab8a7601f26a/610c995bd5f573418e62eb65_img_11-p-800.jpeg 800w, https://assets.website-files.com/6109925e44b6ab8a7601f26a/610c995bd5f573418e62eb65_img_11.jpg 1000w"
                  sizes="(max-width: 479px) 96vw, (max-width: 767px) 95vw, 96vw"
                  alt=""
                  className={style.image_lightbox}
                />
              </a>
            </div>
            <div className={`${style.w_layout_grid} ${style.grid_galleries___row} ${style.margin}`}>
              <a href="#" className={`${style.lightbox_link} ${style.w_inline_block} ${style.w_lightbox}`}>
                <Image
                  src={img_8}
                  loading="lazy"
                  srcSet="https://assets.website-files.com/6109925e44b6ab8a7601f26a/610c995bd53807b403f4c0b6_img_8-p-500.jpeg 500w, https://assets.website-files.com/6109925e44b6ab8a7601f26a/610c995bd53807b403f4c0b6_img_8-p-800.jpeg 800w, https://assets.website-files.com/6109925e44b6ab8a7601f26a/610c995bd53807b403f4c0b6_img_8.jpg 1000w"
                  sizes="(max-width: 479px) 96vw, (max-width: 767px) 95vw, 96vw"
                  alt=""
                  className={style.image_lightbox}
                />
              </a>
              <a href="#" className={`${style.lightbox_link} ${style.w_inline_block} ${style.w_lightbox}`}>
                <Image
                  src={img_5}
                  loading="lazy"
                  srcSet="https://assets.website-files.com/6109925e44b6ab8a7601f26a/610c995bd538075c43f4c0b7_img_5-p-500.jpeg 500w, https://assets.website-files.com/6109925e44b6ab8a7601f26a/610c995bd538075c43f4c0b7_img_5.jpg 672w"
                  sizes="(max-width: 479px) 96vw, (max-width: 767px) 95vw, 96vw"
                  alt=""
                  className={style.image_lightbox}
                />
              </a>
            </div>
            <div className={`${style.w_layout_grid} ${style.grid_galleries___row}`}>
              <a href="#" className={`${style.lightbox_link} ${style.w_inline_block} ${style.w_lightbox}`}>
                <Image
                  src={img_6}
                  loading="lazy"
                  srcSet="https://assets.website-files.com/6109925e44b6ab8a7601f26a/610c995bdafde34ebec2fcda_img_6-p-500.jpeg 500w, https://assets.website-files.com/6109925e44b6ab8a7601f26a/610c995bdafde34ebec2fcda_img_6.jpg 745w"
                  sizes="(max-width: 479px) 96vw, (max-width: 767px) 95vw, 96vw"
                  alt=""
                  className={style.image_lightbox}
                />
              </a>
              <a href="#" className={`${style.lightbox_link} ${style.w_inline_block} ${style.w_lightbox}`}>
                <Image
                  src={img_10}
                  loading="lazy"
                  style={{ opacity: 1 }}
                  alt=""
                  className={style.image_lightbox}
                />
              </a>
            </div>
            <div className={`${style.w_layout_grid} ${style.grid_galleries___row} ${style.margin}`}>
              <a href="#" className={`${style.lightbox_link} ${style.w_inline_block} ${style.w_lightbox}`}>
                <Image
                  src={img_9}
                  loading="lazy"
                  style={{ opacity: 1 }}
                  srcSet="https://assets.website-files.com/6109925e44b6ab8a7601f26a/610c995b895b7a5ff922e5e9_img_9-p-800.jpeg 800w, https://assets.website-files.com/6109925e44b6ab8a7601f26a/610c995b895b7a5ff922e5e9_img_9.jpg 1000w"
                  sizes="(max-width: 479px) 96vw, (max-width: 767px) 95vw, 96vw"
                  alt=""
                  className={style.image_lightbox}
                />
              </a>
              <a href="#" className={`${style.lightbox_link} ${style.w_inline_block} ${style.w_lightbox}`}>
                <Image
                  src={img_7}
                  loading="lazy"
                  style={{ opacity: 1 }}
                  srcSet="https://assets.website-files.com/6109925e44b6ab8a7601f26a/610c995b85d7d7248a813449_img_7-p-500.jpeg 500w, https://assets.website-files.com/6109925e44b6ab8a7601f26a/610c995b85d7d7248a813449_img_7.jpg 674w"
                  sizes="(max-width: 479px) 96vw, (max-width: 767px) 95vw, 96vw"
                  alt=""
                  className={style.image_lightbox}
                />
              </a>
            </div>
          </div>
        </div>
      </div>

      {/* S7 */}
      <div className={`${style.section} ${style.shape_section}`}>
        <div className={style.roadmap_shape_testimonial} />
        <div className={style.content}>
          <div className={`${style.block_heading} ${style.margin}`}>
            <Image
              src={logo_familia}
              loading="lazy"
              alt=""
              width={62}
              className={style.image_subtitle}
            />
            <div className={style.subtitle}>
              Testimonios
              <br />
            </div>
            <h2 className={style.heading}>Lo que dicen sobre ellos</h2>
          </div>
          <div className={`${style.slider_testimonials} ${style.w_slider}`}>
            <div className={`mask ${style.w_slider_mask}`} id="w-slider-mask-0">
              <div className={`${style.slide} ${style.w_slide}`}>
                <div className={style.testimonial} aria-hidden="true">
                  <Image
                    src={flower_1}
                    loading="lazy"
                    alt=""
                    className={style.image_testimonial}
                  />
                  <p className={style.paragraph_testimonial} aria-hidden="true">
                    “Turpis nullam dictum semper non. Sit libero venenatis nec, id
                    viverra adipiscing non ultrices volutpat. Eleifend mi augue mi
                    auctor diam diam. Mattis elementum ullamcorper gravida id velit
                    mauris adipiscing sed. Sollicitudin in laoreet etiam.”
                  </p>
                  <div className={style.signature_testimonial} aria-hidden="true">
                    Javier Alonso
                  </div>
                </div>
              </div>
            </div>
            <div
              className={`${style.left_arrow} ${style.w_slider_arrow_left}`}
              role="button"
            >
              <Image
                src={left_arrow}
                loading="lazy"
                width={23}
                alt=""
                className={style.arrow}
              />
            </div>
            <div
              className={`${style.right_arrow} ${style.w_slider_arrow_right}`}
            >
              <Image
                src={right_arrow}
                loading="lazy"
                width={23}
                alt=""
                className={style.arrow}
              />
            </div>
          </div>
        </div>
      </div>

      {/* S8 */}
      <div className={`${style.section} ${style.shape_section}`}>
        <div className={style.roadmap_shape_center} />
        <div className={style.content}>
          <div
            className={`${style.w_layout_grid} ${style.grid_postcard}`}
          >
            <div
              id={style["w-node-bd4b83d7-4172-b584-e8bd-71526bc48981-6c01f26c"]}
              className={style.postcard___block_left}
            >
              <div className={style.postcard_text}>
                <Image
                  src={logo_familia}
                  loading="lazy"
                  alt=""
                  width={62}
                  className={style.image_subtitle}
                />
                <div className={style.subtitle}>
                  él
                  <br />
                </div>
                <h2 className={style.heading}>Historia de Él</h2>
                <p className={style.paragraph}>
                  Velit sagittis donec varius est mus donec donec. Molestie enim id
                  amet elementum adipiscing id consectetur consectetur. Nunc aliquam.
                </p>
                <a href="#" className={`${style.button} ${style.w_button}`}>
                  Más sobre él
                </a>
              </div>
            </div>
            <div
              id={style["w-node-bd4b83d7-4172-b584-e8bd-71526bc4898d-6c01f26c"]}
              className={style.postcard___image}
            >
              <div className={style.overflow_image}>
                <Image
                  src={img_12}
                  loading="lazy"
                  srcSet="https://assets.website-files.com/6109925e44b6ab8a7601f26a/610df60220b64c18e8457e38_img_12-p-500.jpeg 500w, https://assets.website-files.com/6109925e44b6ab8a7601f26a/610df60220b64c18e8457e38_img_12-p-800.jpeg 800w, https://assets.website-files.com/6109925e44b6ab8a7601f26a/610df60220b64c18e8457e38_img_12.jpg 805w"
                  sizes="(max-width: 479px) 96vw, (max-width: 767px) 95vw, 96vw"
                  alt=""
                  className={style.image}
                />
              </div>
              <Image
                src={flower_2}
                loading="eager"
                alt=""
                className={style.flower_postcard___c}
              />
              <Image
                src={flower_5}
                loading="eager"
                alt=""
                className={style.flower_postcard___d}
              />
            </div>
          </div>
        </div>
      </div>

      <Footer />

    </>
  )
}
